### ISSUE TITLE
RPC connection times out after a while

### ISSUE THREAD

**Issue by jonas-schievink** [atroche/rust-headless-chrome#142]
When I navigate to a tab and then do nothing for a couple of seconds while keeping the `Browser` instance around, eventually an error like the following will be logged:

```
Got a timeout while listening for browser events (Chrome #Some(28734))
```

Is there a way to avoid this, other than restarting the whole browser after this happens? I haven't found a way to configure timeouts in the documentation.

**Comment by atroche** [comment]
Ah, sorry about that. I'll either make it configurable, or just not time out in the first place -- I can't remember why I started doing that in the first place.

In the meantime as a workaround you could do a no-op like querying the DOM every so often.

On Tue, 30 Jul 2019, at 7:41 AM, Jonas Schievink wrote:
> When I navigate to a tab and then do nothing for a couple of seconds while keeping the `Browser` instance around, eventually an error like the following will be logged:

> `Got a timeout while listening for browser events (Chrome #Some(28734))
`

**Comment by jonas-schievink** [comment]
Hmm, the same also seems to happen when the `Browser` is dropped and I try to use a `Tab` from that browser instance.

**Comment by atroche** [comment]
That same error message? Strange.

Do you have steps to reproduce?

**Comment by jonas-schievink** [comment]
This is enough to trigger the second case:

```rust
fn main() {
    env_logger::init();

    let browser = headless_chrome::Browser::default().unwrap();
    let tab = browser.new_tab().unwrap();
    drop(browser);

    tab.navigate_to("https://google.com").unwrap();
}
```

This panics with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionClosed

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::heb1fa3adca37e9da (0x5574bf67bf23)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h4d905dfc1daea1c8 (0x5574bf67bcce)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::hcd32f4b79305d2bd (0x5574bf16e017)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
   3: <failure::error::Error as core::convert::From<F>>::from::h3734488f12893e89 (0x5574bf08d1ba)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
   4: <T as core::convert::Into<U>>::into::h202c72caf68669d7 (0x5574bf0222fa)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/convert.rs:540
   5: headless_chrome::browser::transport::Transport::call_method::h461400072f6bfee5 (0x5574bf0231d1)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/transport/mod.rs:120
   6: headless_chrome::browser::transport::Transport::call_method_on_target::h53f5131167aa329b (0x5574bf035ab3)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/transport/mod.rs:179
   7: headless_chrome::browser::tab::Tab::call_method::he03a5ececf9d7784 (0x5574bf178a0f)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/tab/mod.rs:246
   8: headless_chrome::browser::tab::Tab::navigate_to::h54b88f7b6c777b41 (0x5574bf179343)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/tab/mod.rs:271
   9: headless_repro::main::h37748a776110e6bd (0x5574bf003b93)
             at src/main.rs:8
```

**Comment by atroche** [comment]
Oh, I thought you meant it gave the same "timeout" error.

What behaviour would you prefer to see when calling a tab's method after dropping the browser?

On Tue, 30 Jul 2019, at 8:25 AM, Jonas Schievink wrote:
> This is enough to trigger the second case:

> fn main() {
    env_logger::init();

    let browser = headless_chrome::Browser::default().unwrap();
    let tab = browser.new_tab().unwrap();
    drop(browser);

    tab.navigate_to("https://google.com").unwrap();
}
> This panics with:

> `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionClosed

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::heb1fa3adca37e9da (0x5574bf67bf23)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h4d905dfc1daea1c8 (0x5574bf67bcce)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::hcd32f4b79305d2bd (0x5574bf16e017)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
   3: <failure::error::Error as core::convert::From<F>>::from::h3734488f12893e89 (0x5574bf08d1ba)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
   4: <T as core::convert::Into<U>>::into::h202c72caf68669d7 (0x5574bf0222fa)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/convert.rs:540
   5: headless_chrome::browser::transport::Transport::call_method::h461400072f6bfee5 (0x5574bf0231d1)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/transport/mod.rs:120
   6: headless_chrome::browser::transport::Transport::call_method_on_target::h53f5131167aa329b (0x5574bf035ab3)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/transport/mod.rs:179
   7: headless_chrome::browser::tab::Tab::call_method::he03a5ececf9d7784 (0x5574bf178a0f)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/tab/mod.rs:246
   8: headless_chrome::browser::tab::Tab::navigate_to::h54b88f7b6c777b41 (0x5574bf179343)
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/headless_chrome-0.3.0/src/browser/tab/mod.rs:271
   9: headless_repro::main::h37748a776110e6bd (0x5574bf003b93)
             at src/main.rs:8
`

**Comment by jonas-schievink** [comment]
Ah, right. In both cases it will return `ConnectionClosed`, but what causes it is different.

I'd expect a `Tab` to either keep its associated `Browser` instance alive (or some shared connection object), or to borrow the browser instead so that it must be disposed before the browser (becoming `Tab<'a>`). The latter might be overly restrictive to users though.

**Comment by jonas-schievink** [comment]
Here's some code that reproduces my original issue:

```rust
use std::{thread, time::Duration};

fn main() {
    env_logger::init();

    let browser = headless_chrome::Browser::default().unwrap();
    let tab = browser.new_tab().unwrap();

    tab.navigate_to("https://google.com").unwrap();
    tab.wait_until_navigated().unwrap();

    println!("<<<<<<<<<<< sleeping >>>>>>>>>>>>>>");
    thread::sleep(Duration::from_secs(20));
    println!("<<<<<<<<<<< slept >>>>>>>>>>>>>>");

    browser.new_tab().unwrap();

    thread::sleep(Duration::from_secs(5));
}
```

Only when using the `browser` after the sleep, an error happens. When using just the `tab`, a few warnings get logged, but no errors are returned.

**Comment by atroche** [comment]
Thanks, that's helpful. I'm not sure how quickly I'll be able to improve this; work's busy for me for the next couple of weeks.

To anyone who feels like taking this on, grepping for the timeout error should take you near the relevant constant to be replaced (with a parameter / config option, presumably in the LaunchOptions struct in the process module).

On Tue, 30 Jul 2019, at 8:43 AM, Jonas Schievink wrote:
> Here's some code that reproduces my original issue:

> use std::{thread, time::Duration};

> fn main() {
    env_logger::init();

    let browser = headless_chrome::Browser::default().unwrap();
    let tab = browser.new_tab().unwrap();

    tab.navigate_to("https://google.com").unwrap();
    tab.wait_until_navigated().unwrap();

    println!("<<<<<<<<<<< sleeping >>>>>>>>>>>>>>");
    thread::sleep(Duration::from_secs(20));
    println!("<<<<<<<<<<< slept >>>>>>>>>>>>>>");

    browser.new_tab().unwrap();

    thread::sleep(Duration::from_secs(5));
}

**Comment by jeprojects** [comment]
@atroche I can take a look at it. Just a few questions to make sure I am going to do it right.

There is a `Process` struct which is accessible in `Browser` struct

```
pub struct Process {
    child_process: TemporaryProcess,
    pub debug_ws_url: String,
}

pub struct Browser {
    process: Option<Process>,
    transport: Arc<Transport>,
    tabs: Arc<Mutex<Vec<Arc<Tab>>>>,
    loop_shutdown_tx: mpsc::Sender<()>,
}
```
I can then modify LaunchOptions and when creating the Process struct, put it in there.

Should I store it there? If so, under what name would be suitable?

Next your `fn handle_browser_level_events` can then get the timeout value from `Browser.process`

**Comment by atroche** [comment]
Ah, I actually wouldn't store it, because `handle_browser_level_events` is only called once on startup, and the timeout value never needs to be referenced again.

Re. name, `idle_browser_timeout` (of type `Duration`) is the first thing that pops into my head. For the docstring you could say something like "how long to keep the WebSocket to the browser for after not receiving any events from it").

I'm realising that ideally LaunchOptions would be in `browser`, not `process`, but that's probably a change for another day.

Also, is there any way you could make LaunchOptions more visible / obvious in the docs, or to fix that dead link in the `Browser` docstring? NBD if not.

Thanks for the help!

**Comment by jeprojects** [comment]
So would having it as a function parameter be ok?

Example:

In Browser:

`pub fn new(launch_options: LaunchOptions)`

which calls: 
`fn create_browser(process: Option<Process>, transport: Arc<Transport>, idle_browser_timeout: Duration)`

which then calls:
```
fn handle_browser_level_events(
        &self,
        events_rx: mpsc::Receiver<Event>,
        process_id: Option<u32>,
        shutdown_rx: mpsc::Receiver<()>,
       idle_browser_timeout: Duration,
    )
```

**Comment by atroche** [comment]
yeah, that makes sense.

**Comment by jeprojects** [comment]
https://github.com/atroche/rust-headless-chrome/pull/145

**Comment by timbodeit** [comment]
@atroche As a constumer of the API I would not expect the browser connection to time out while I'm still holding it. Do you recall what the benefit of having this timeout is? Wouldn't it be more intuitive to just remove the timeout entirely?
