### ISSUE TITLE
Browser::default() panicks instead of fetching when no Chrome executable is found.

### ISSUE THREAD

**Issue by timbodeit** [atroche/rust-headless-chrome#226]
**Expected behavior:**
When `fetch` feature is enabled, calling `Browser::default()` should automatically download a chromium binary if none is found on the system.

**Actual behavior:**
`Browser::default` panicks due to `unwrap()` call in the definition of `launch_options`.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Could not auto detect a chrome executable"', /home/pi/rust-headless-chrome/src/browser/mod.rs:102:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/result.rs:973:23
   4: headless_chrome::browser::Browser::default
             at /home/pi/rust-headless-chrome/src/browser/mod.rs:102:24
[...]
```

**Comment by alexzanderr** [comment]
yeah, it should.

if you look at the source code:

```rust
/// Returns the path to Chrome's executable.
///
/// If the `CHROME` environment variable is set, `default_executable` will
/// use it as the default path. Otherwise, the filenames `google-chrome-stable`
/// `chromium`, `chromium-browser`, `chrome` and `chrome-browser` are
/// searched for in standard places. If that fails,
/// `/Applications/Google Chrome.app/...` (on MacOS) or the registry (on Windows)
/// is consulted. If all of the above fail, an error is returned.
pub fn default_executable() -> Result<std::path::PathBuf, String> {
    if let Ok(path) = std::env::var("CHROME") {
        if std::path::Path::new(&path).exists() {
            return Ok(path.into());
        }
    }

    for app in &[
        "google-chrome-stable",
        "chromium",
        "chromium-browser",
        "chrome",
        "chrome-browser",
    ] {
        if let Ok(path) = which(app) { // here returns the path to ALREADY installed chromium, doesnt auto install
            return Ok(path);
        }
    }

    #[cfg(target_os = "macos")]
    {
        let default_paths = &["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"][..];
        for path in default_paths {
            if std::path::Path::new(path).exists() {
                return Ok(path.into());
            }
        }
    }

    #[cfg(windows)]
    {
        use crate::browser::process::get_chrome_path_from_registry;

        if let Some(path) = get_chrome_path_from_registry() {
            if path.exists() {
                return Ok(path);
            }
        }
    }

    Err("Could not auto detect a chrome executable".to_string())
}
```

for short, this checks if chromium is installed on your system.

if it is -> then opens the one found in headless mode
if it isnt -> fails dramatically

there is no auto install, i've looked in the source code.

you have to install `chromium` manually.

for me, being on arch linux it was: `sudo pacman -S chromium`

for other distros: use your package manager, you are linux user, not windows user.

**Comment by alexzanderr** [comment]
conclusion: `installing` the `chromium` `manually` `will fix` the issue, peace to you!

**Comment by epompeii** [comment]
The solution that worked for me was to not use `Browser::default()`.

Instead you need to use the `Browser::new()` method:

```
let launch_options = LaunchOptions::default();
let browser = Browser::new(launch_options)?;
```

It is counter-intuitive, but the two are semantically different.

**Comment by ezalorsara** [comment]
Hi, How to do this  "installing the chromium manually will fix" in aws lambda.
