### ISSUE TITLE
register_response_handling for XHRs

### ISSUE THREAD

**Issue by remykarem** [atroche/rust-headless-chrome#326]
I cannot seem to read the XHR responses using `register_response_handling`. Is there a way to do this?

Here's my code:

```rust
use std::error::Error;
use std::thread::sleep;
use std::time::Duration;

use headless_chrome::{Browser, LaunchOptions};

fn main() -> Result<(), Box<dyn Error>> {
    let browser = Browser::new(
        LaunchOptions::default_builder()
            .headless(false)
            .build()
            .expect("Could not find chrome-executable"),
    )?;

    let tab = browser.wait_for_initial_tab()?;

    tab.navigate_to("https://www.google.com")?;

    tab.register_response_handling(
        "handler",
        Box::new(move |response, _fetch_body| {
            println!("{:?}", response.response.url);
        }),
    )?;

    sleep(Duration::from_secs(10));

    Ok(())
}
```

**Comment by mdrokz** [comment]
> I cannot seem to read the XHR responses using `register_response_handling`. Is there a way to do this?
> 
> Here's my code:
> 
> ```rust
> use std::error::Error;
> use std::thread::sleep;
> use std::time::Duration;
> 
> use headless_chrome::{Browser, LaunchOptions};
> 
> fn main() -> Result<(), Box<dyn Error>> {
>     let browser = Browser::new(
>         LaunchOptions::default_builder()
>             .headless(false)
>             .build()
>             .expect("Could not find chrome-executable"),
>     )?;
> 
>     let tab = browser.wait_for_initial_tab()?;
> 
>     tab.navigate_to("https://www.google.com")?;
> 
>     tab.register_response_handling(
>         "handler",
>         Box::new(move |response, _fetch_body| {
>             println!("{:?}", response.response.url);
>         }),
>     )?;
> 
>     sleep(Duration::from_secs(10));
> 
>     Ok(())
> }
> ```

your using an outdated version of rust-headless-chrome please use the latest git version, 

check this 

https://github.com/atroche/rust-headless-chrome/blob/f8012ec4ed867ccc0efa6b262723363afd775011/tests/simple.rs#L585-L631

**Comment by remykarem** [comment]
Correct me if I'm wrong - this seems like it's intercepting outgoing requests.

I'm looking for intercepting incoming responses, which is why I used `register_response_handling`.

I tried calling running the code below (navigating to google.com)

```rust
use std::sync::Mutex;
use std::{error::Error, sync::Arc};
use std::thread::sleep;
use std::time::Duration;

use headless_chrome::{Browser, LaunchOptions};

fn main() -> Result<(), Box<dyn Error>> {
    let browser = Browser::new(
        LaunchOptions::default_builder()
            .headless(false)
            .build()
            .expect("Could not find chrome executable"),
    )?;

    let tab = browser.wait_for_initial_tab()?;

    let responses = Arc::new(Mutex::new(Vec::new()));
    let responses2 = responses.clone();
    let responses3 = responses.clone();
    assert_eq!(tab.register_response_handling("test1",Box::new(move |response, fetch_body| {
        // NOTE: you can only fetch the body after it's been downloaded, which might be some time
        // after the initial 'response' (with status code, headers, etc.) has come back. hence this
        // sleep:
        sleep(Duration::from_millis(500));
        let body = fetch_body().unwrap();
        responses2.lock().unwrap().push((response, body));
    }))?.is_none(), true);

    assert_eq!(tab.register_response_handling("test2",Box::new(move |response, fetch_body| {
        // NOTE: you can only fetch the body after it's been downloaded, which might be some time
        // after the initial 'response' (with status code, headers, etc.) has come back. hence this
        // sleep:
        sleep(Duration::from_millis(500));
        let body = fetch_body().unwrap();
        responses3.lock().unwrap().push((response, body));
    }))?.is_none(), true);


    tab.navigate_to("https://www.google.com")?;
    tab.wait_until_navigated()?;

    let final_responses: Vec<_> = responses.lock().unwrap().clone();
    assert_eq!(final_responses.len(), 3 * 2);
    assert_eq!(final_responses[0].0.response.mime_type, "text/html");

    Ok(())
}
```

and got

```txt
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Method call error -32000: No resource with given identifier found', src/bin/scratch.rs:27:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Couldn't send event to listener: SendError { .. }', /Users/xxx/.cargo/git/checkouts/rust-headless-chrome-fd32a97e7a7fa8b4/e867637/src/browser/transport/mod.rs:297:58
Error: The event waited for never came
```

**Comment by mdrokz** [comment]
> Correct me if I'm wrong - this seems like it's intercepting outgoing requests.
> 
> I'm looking for intercepting incoming responses, which is why I used `register_response_handling`.
> 
> I tried calling running the code below (navigating to google.com)
> 
> ```rust
> use std::sync::Mutex;
> use std::{error::Error, sync::Arc};
> use std::thread::sleep;
> use std::time::Duration;
> 
> use headless_chrome::{Browser, LaunchOptions};
> 
> fn main() -> Result<(), Box<dyn Error>> {
>     let browser = Browser::new(
>         LaunchOptions::default_builder()
>             .headless(false)
>             .build()
>             .expect("Could not find chrome executable"),
>     )?;
> 
>     let tab = browser.wait_for_initial_tab()?;
> 
>     let responses = Arc::new(Mutex::new(Vec::new()));
>     let responses2 = responses.clone();
>     let responses3 = responses.clone();
>     assert_eq!(tab.register_response_handling("test1",Box::new(move |response, fetch_body| {
>         // NOTE: you can only fetch the body after it's been downloaded, which might be some time
>         // after the initial 'response' (with status code, headers, etc.) has come back. hence this
>         // sleep:
>         sleep(Duration::from_millis(500));
>         let body = fetch_body().unwrap();
>         responses2.lock().unwrap().push((response, body));
>     }))?.is_none(), true);
> 
>     assert_eq!(tab.register_response_handling("test2",Box::new(move |response, fetch_body| {
>         // NOTE: you can only fetch the body after it's been downloaded, which might be some time
>         // after the initial 'response' (with status code, headers, etc.) has come back. hence this
>         // sleep:
>         sleep(Duration::from_millis(500));
>         let body = fetch_body().unwrap();
>         responses3.lock().unwrap().push((response, body));
>     }))?.is_none(), true);
> 
> 
>     tab.navigate_to("https://www.google.com")?;
>     tab.wait_until_navigated()?;
> 
>     let final_responses: Vec<_> = responses.lock().unwrap().clone();
>     assert_eq!(final_responses.len(), 3 * 2);
>     assert_eq!(final_responses[0].0.response.mime_type, "text/html");
> 
>     Ok(())
> }
> ```
> 
> and got
> 
> ```
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Method call error -32000: No resource with given identifier found', src/bin/scratch.rs:27:33
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread '<unnamed>' panicked at 'Couldn't send event to listener: SendError { .. }', /Users/xxx/.cargo/git/checkouts/rust-headless-chrome-fd32a97e7a7fa8b4/e867637/src/browser/transport/mod.rs:297:58
> Error: The event waited for never came
> ```

the above code can intercept both outgoing and incoming since we specify the pattern `RequestStage::Response`
```rust
let patterns = vec![ 
         RequestPattern { 
             url_pattern: None, 
             resource_Type: None, 
             request_stage: Some(RequestStage::Response), 
         }, 
         RequestPattern { 
             url_pattern: None, 
             resource_Type: None, 
             request_stage: Some(RequestStage::Request), 
         }, 
     ]; 
     tab.enable_fetch(Some(&patterns), None)?; 
```

**Comment by remykarem** [comment]
Do you have an example where an XHR response type is intercepted?

**Comment by mdrokz** [comment]
> Do you have an example where an XHR response type is intercepted?

you can try this example

```rs
#[test]
fn set_request_interception() -> Result<()> {
    logging::enable_logging();
    let (server, browser, tab) = dumb_server(include_str!(
        "coverage_fixtures/basic_page_with_js_scripts.html"
    ));

    let patterns = vec![
        RequestPattern {
            url_pattern: None,
            resource_Type: None,
            request_stage: Some(RequestStage::Response),
        },
        RequestPattern {
            url_pattern: None,
            resource_Type: None,
            request_stage: Some(RequestStage::Request),
        },
    ];
    tab.enable_fetch(Some(&patterns), None)?;

    tab.enable_request_interception(Arc::new(
        move |transport: Arc<Transport>, session_id: SessionId, intercepted: RequestPausedEvent| {
            if intercepted.params.request.url.ends_with(".js") {
                let js_body = r#"document.body.appendChild(document.createElement("hr"));"#;

                let headers = vec![HeaderEntry {
                    name: "Content-Type".to_string(),
                    value: "application/javascript".to_string(),
                }];

                let fulfill_request = FulfillRequest {
                    request_id: intercepted.params.request_id,
                    response_code: 200,
                    response_headers: Some(headers),
                    binary_response_headers: None,
                    body: Some(base64::encode(js_body)),
                    response_phrase: None,
                };

                RequestPausedDecision::Fulfill(fulfill_request)
            } else {
                RequestPausedDecision::Continue(None)
            }
        },
    ))?;
```

**Comment by remykarem** [comment]
That’s not intercepting an XHR request, does it? Do you have an example for a real website that intercepts XHR requests?
